openapi: 3.0.0
info:
  title: Job API
  contact: {}
  version: '1.0'
servers:
- url: https://job-api-example.herokuapp.com/api/v1
  variables: {}
paths:
  /auth/register:
    post:
      tags:
      - Auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: 'Request email, name and password to register'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example:
              email: abc@gmail.com
              name: Vu Thi Thanh Thuy
              password: '123456'
        required: true
      responses:
        '200':
          description: 'Json containing user info, message and user token'
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg: 
                    type: string
                  user:
                    type: object
                    properties: 
                      name :
                        type: string
                      mail :
                        type: string
                  token:
                    type: string
              example:
                msg: Registered successfully
                user:
                  name : Nguyen Tan Hung
                  mail : nguyentanhung@gmail.com  
                token: Token
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: 'Require email and password to logins'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              email: nguyentanhung@gmail.com
              password: Hung9090
        required: true
      responses:
        '200':
          description: 'Json containing user info, message and user token'
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg: 
                    type: string
                  user:
                    type: object
                    properties: 
                      name :
                        type: string
                  token:
                    type: string
              example:
                msg: Logined successfully
                user: 
                  name : 'Nguyen Tan Hung'
                token: 'Token'
      deprecated: false
      security: []
  /auth/forgot:
    post:
      tags:
      - Auth
      summary: Forgot Password
      operationId: ForgotPassword
      parameters: []
      requestBody:
        description: 'Require email of user'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
            example:
              email: nguyentanhung@gmail.com
        required: true
      responses:
        '200':
          description: 'Send Back Email To User, Including Link To Reset Password'
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg: 
                    type: string
                  forgotPasswordToken:
                    type: string
              example:
                msg: Sent password request to email successfully
      deprecated: false

  /jobs:
    post:
      tags:
      - Job
      summary: Create Jobs
      operationId: CreateJobs
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobsRequest'
            example:
              company: Test
              position: Test
        required: true
      responses:
        '200':
          description: 'Return job object if create success'
          headers: {}
          content:
            application/json:
              schema:
                type: object
                  properties:
                    msg:
                      type: string
                    job:
                      type: object
                      properties:
                        status:
                          type: string
                        _id:
                          type: string
                        company:
                          type: string
                        position:
                          type: string
                        createdBy:
                          type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                        __v:
                          type: number
              example:
                msg : Created job successfully
                job:           
                    status: pending          
                    _id: 62d7a56dbae0d436c47a58e9
                    company: Enclave
                    position: Cadet
                    createdBy: 62d50d26408b151974cff860
                    createdAt: '2022-07-20T06:49:17.843Z'
                    updatedAt: '2022-07-20T06:49:17.843Z'    
                    __v: '0'
      deprecated: false
      security:
      - bearer: []
    get:
      tags:
      - Job
      summary: Get All Job
      operationId: GetAllJob
      parameters: []
      responses:
        '200':
          description: 'Return array of jobs'
          headers: {}
          content:
            application/json:
              schema:
                type: object
                  properties:
                    jobs:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: string
                          _id:
                            type: string
                          company:
                            type: string
                          position:
                            type: string
                          createdBy:
                            type: string
                          createdAt:
                            type: string
                          updatedAt:
                            type: string
                          __v:
                            type: number
                    count:
                      type: number
              example:
                job:             
                    - status: pending          
                      _id: 62d7a56dbae0d436c47a58e9
                      company: Enclave
                      position: Cadet
                      createdBy: 62d50d26408b151974cff860
                      createdAt: '2022-07-20T06:49:17.843Z'
                      updatedAt: '2022-07-20T06:49:17.843Z'    
                      __v: '0'
                    - status: pending          
                      _id: 62d7a56dbae0d436c47a58e9
                      company: Google
                      position: Senior Back End Developer
                      createdBy: 62d50d26408b151974cff860
                      createdAt: '2022-07-20T06:49:17.843Z'
                      updatedAt: '2022-07-20T06:49:17.843Z'    
                      __v: '0'
                count: '4'
      deprecated: false
      security:
      - bearer: []
  /jobs/{id}:
    get:
      tags:
      - Job
      summary: Get One Job
      operationId: GetOneJob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  job:
                    type: object
                    properties:
                      status:
                        type: string
                      _id:
                        type: string
                      company:
                        type: string
                      position:
                        type: string
                      createdBy:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      __v:
                        type: number
              example:           
                job:           
                  status: pending          
                  _id: 62d7a56dbae0d436c47a58e9
                  company: Enclave
                  position: Cadet
                  createdBy: 62d50d26408b151974cff860
                  createdAt: '2022-07-20T06:49:17.843Z'
                  updatedAt: '2022-07-20T06:49:17.843Z'    
                  __v: '0'
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://job-api-example.herokuapp.com/api/v1
        variables: {}
    patch:
      tags:
      - Job
      summary: Update Job
      operationId: UpdateJob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
            example:
              company: Random
              position: Random
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                  properties:
                    msg:
                      type: string
                    job:
                      type: object
                      properties:
                        status:
                          type: string
                        _id:
                          type: string
                        company:
                          type: string
                        position:
                          type: string
                        createdBy:
                          type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                        __v:
                          type: number
              example:
                msg : Updated Job Successfully
                job:           
                    status: pending          
                    _id: 62d7a56dbae0d436c47a58e9
                    company: Enclave
                    position: Cadet
                    createdBy: 62d50d26408b151974cff860
                    createdAt: '2022-07-20T06:49:17.843Z'
                    updatedAt: '2022-07-20T06:49:17.843Z'    
                    __v: '0'
      deprecated: false
      security:
      - bearer: []
    delete:
      tags:
      - Job
      summary: Delete Job
      operationId: DeleteJob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                  properties:
                    msg:
                      type: string
              example:
                msg : Deleted Job Successfully
      deprecated: false
      security:
      - bearer: []
components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        email: nguyentanhung@gmail.com
        password: Hung9090
        name: Nguyen Tan Hung
    LoginRequest:
      title: LoginRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: nguyentanhung@gmail.com
        password: Hung9090
    CreateJobsRequest:
      title: CreateJobsRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Test
        position: Test
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Random
        position: Random
    ForgotPasswordRequest:
      title: ForgotPasswordRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: nguyentanhung@gmail.com
    ResetPasswordRequest:
      title: ResetPasswordRequest
      required:
      - newPassword
      type: object
      properties:
        newPassword:
          type: string
      example:
        newPassword: '987654'
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Misc
  description: ''
- name: Auth
  description: ''
- name: Job
  description: ''